version: '3.8'

services:
  aifeedback-web:
    build:
      context: . # Контекст сборки - корневая папка решения
      dockerfile: AIFeedback/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ollama-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Оставляем Development для жюри, чтобы были видны ошибки, если что-то пойдет не так

  ollama-server:
    image: ollama/ollama:latest
    container_name: aifeedback-ollama-server-1
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      
volumes:
  ollama_data: