// <auto-generated />
using System;
using AIFeedback.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIFeedback.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260822195024_New5")]
    partial class New5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AIFeedback.Data.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiInsightsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AvailabilityAvg")
                        .HasColumnType("REAL");

                    b.Property<double>("AvailabilityMedian")
                        .HasColumnType("REAL");

                    b.Property<double>("AvailabilityStdDev")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgAccessibility")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgEngagement")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgPractice")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgUtility")
                        .HasColumnType("REAL");

                    b.Property<string>("CorrelationMatrixJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateProcessed")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetachedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dist1to3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dist4to7")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dist8to10")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicateRowsRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EngagedCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EngagementYesPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("FormatMixedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormatOfflineCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormatOnlineCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InteractionAvg")
                        .HasColumnType("REAL");

                    b.Property<double>("InteractionMedian")
                        .HasColumnType("REAL");

                    b.Property<double>("InteractionStdDev")
                        .HasColumnType("REAL");

                    b.Property<int>("ListenerCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OverallSatisfaction")
                        .HasColumnType("REAL");

                    b.Property<double>("PracticalityAvg")
                        .HasColumnType("REAL");

                    b.Property<double>("PracticalityMedian")
                        .HasColumnType("REAL");

                    b.Property<double>("PracticalityStdDev")
                        .HasColumnType("REAL");

                    b.Property<string>("ProblemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoresDistributionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentimentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendLabelsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendValuesJson")
                        .HasColumnType("TEXT");

                    b.Property<double>("UsefulnessAvg")
                        .HasColumnType("REAL");

                    b.Property<double>("UsefulnessMedian")
                        .HasColumnType("REAL");

                    b.Property<double>("UsefulnessStdDev")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AnalysisResults");
                });
#pragma warning restore 612, 618
        }
    }
}
