// <auto-generated />
using System;
using AIFeedback.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIFeedback.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AIFeedback.Data.AnalysisResult", b =>
                {
                    b.Property<string>("SessionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiInsightsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AvailabilityAvg")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgAccessibility")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgEngagement")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgPractice")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgUtility")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateProcessed")
                        .HasColumnType("TEXT");

                    b.Property<double>("EngagementYesPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InteractionAvg")
                        .HasColumnType("REAL");

                    b.Property<int>("ListenerCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OverallSatisfaction")
                        .HasColumnType("REAL");

                    b.Property<double>("PracticalityAvg")
                        .HasColumnType("REAL");

                    b.Property<string>("ProblemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentimentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UsefulnessAvg")
                        .HasColumnType("REAL");

                    b.HasKey("SessionName");

                    b.ToTable("AnalysisResults");
                });
#pragma warning restore 612, 618
        }
    }
}
